puppycompanyblog/blogpost/forms.py
#inside blogpost.forms.py file

from flask_wtf import FlaskForm
from wtforms import StringField , SubmitField
from wtforms.validators import DataRequired


class BlogPostForm(FlaskForm):

    title = StringField('Title : ' , validators = [DataRequired()])
    text = StringField('Text : ' , validators = [DataRequired()])
    submit = SubmitField('Create Post')

    

puppycompanyblog/blogpost/views.py
# inside blogpost.views.py file #
from flask import render_template , redirect , url_for , request , flash , abort , Blueprint
from puppycompanyblog import db
from puppycompanyblog.models import BlogPost
from puppycompanyblog.blogpost.forms import BlogPostForm
from flask_login import login_required , current_user

blog_posts = Blueprint('blog_posts' , __name__)


# create post
@blog_posts.route('/create' , methods = ['GET' , 'POST'])
@login_required
def create_post():

    form = BlogPostForm()

    if form.validate_on_submit():

        post = BlogPost(title = form.title.data , text = form.text.data , user_id = current_user.id)
        db.session.add(post)
        db.session.commit()
        flash('Post created successfully!')
        return redirect(url_for('core.home'))

    return render_template('create_post.html' , form = form)


# read post(blog_post view)
@blog_posts.route('/<int:blog_post_id>')
def blog_post(blog_post_id):

    blog_post = BlogPost.query.get_or_404(blog_post_id)
    return render_template('blog_post.html' , post = blog_post)




# update post
@blog_posts.route('/<int:blog_post_id>/update', methods = ['GET' , 'POST'])
@login_required
def update(blog_post_id):

    post = BlogPost.query.get_or_404(blog_post_id)

    if post.author != current_user:
        abort(403)

    form = BlogPostForm()

    if form.validate_on_submit():

        post.title = form.title.data
        post.text = form.text.data

        db.session.commit()
        flash('post updated successfully!')
        return redirect(url_for('core.home'))

    elif(request.method == 'GET'):

        form.text.data = post.text
        form.title.data = post.title

    return render_template('create_post.html' , title = 'updating' , form = form)

# delete post
@blog_posts.route('/<int:blog_post_id>/delete_post')
@login_required
def delete_post(blog_post_id):

    post = BlogPost.query.get_or_404(blog_post_id)

    if post.author != current_user:
        abort(403)

    db.session.delete(post)
    db.session.commit()
    flash('post deleted successfully!')

    return redirect(url_for('core.home'))

puppycompanyblog/core/views.py
# inside core.views

from flask import render_template , Blueprint , request
from puppycompanyblog.models import BlogPost

core = Blueprint('core' , __name__)


@core.route('/')
def home():
    #MOre to Come#
    page = request.args.get('page' , 1 , type = int)
    blog_posts = BlogPost.query.order_by(BlogPost.date.desc()).paginate(page = page , per_page = 5)
    return render_template('home.html' , blog_posts = blog_posts)


@core.route('/about')
def about():
    return render_template('about.html')


    

puppycompanyblog/users/views.py
#  inside puppycompanyblog.users.views.py file


from flask import render_template , redirect , url_for , request , flash , Blueprint
from flask_login import current_user , login_required , login_user , logout_user
from puppycompanyblog import db
from puppycompanyblog.users.forms import RegisterForm , LoginForm , UpdateForm
from puppycompanyblog.models import User , BlogPost
from puppycompanyblog.users.picture_handler import add_profile_pic

users = Blueprint('users' , __name__)

## register view ##
@users.route('/register' , methods = ['GET' , 'POST'])
def register():
    form = RegisterForm()

    if form.validate_on_submit():

        user = User(email = form.email.data , username = form.username.data , password = form.password.data)

        db.session.add(user)
        db.session.commit()
        flash('User registered successfully!')

        return redirect(url_for('users.login'))


    return render_template('register.html' , form = form)

## login view ##
@users.route('/login' , methods = ['GET' , 'POST'])
def login():
    
    form = LoginForm()

    if form.validate_on_submit():

        user = User.query.filter_by(email = form.email.data).first()

        if user and user.check_password(password = form.password.data):

            login_user(user)
            flash('user logged in successfully!')
            return redirect(url_for('core.home'))

    return render_template('login.html' , form = form)

## logout view ##

@users.route('/logout')
@login_required
def logout():

    logout_user()
    flash('User logout successfully !')
    return redirect(url_for('core.home'))

## update view ##

@users.route('/update' , methods = ['GET' , 'POST'])
@login_required
def update():

    form = UpdateForm()

    if form.validate_on_submit():

        if form.picture.data:
            pic = add_profile_pic(form.picture.data , current_user.username)
            current_user.profile_image = pic

        current_user.username = form.username.data
        current_user.email = form.email.data

        db.session.commit()
        flash('User updated successfully!')

        return redirect(url_for('core.home'))
    elif(request.method == 'GET'):

        form.email.data = current_user.email
        form.username.data = current_user.username

    profile_image = url_for('static' , filename = '/profile_pics' + current_user.profile_image)

    return render_template('update.html' , form = form , profile_image = profile_image)

## user's list of blogposts ##
@users.route('/<string:username>')
def user_posts(username):
    page = request.args.get('page' , 1 , type = int)
    user = User.query.filter_by(username = username).first_or_404()
    blog_posts = BlogPost.query.filter_by(author = user).order_by(BlogPost.date.desc()).paginate(page =page , per_page = 5)
    return render_template('user_blog_posts.html' , blog_posts = blog_posts , user = user)

puppycompanyblog/templates/about.html
{% extends "base.html" %}
{% block content %}
    <div class="jumbotron">
        <p>Lorem, ipsum dolor sit amet consectetur adipisicing elit. Quo, commodi nemo quam obcaecati quaerat aliquam rerum repudiandae corporis laboriosam voluptatibus in nam, pariatur quasi possimus animi mollitia nulla eligendi? Possimus?</p>
    </div>
{% endblock %}

puppycompanyblog/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Major Project - 3</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>

</head>
<body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <a class="navbar-brand" href=" {{ url_for('core.home') }} ">Home</a>
        <a class="navbar-brand" href=" {{ url_for('core.about') }} ">About</a>
        {% if current_user.is_authenticated %}
        <a class="navbar-brand" href=" {{ url_for('users.logout') }} ">Logout</a>
        <a class="navbar-brand" href=" {{ url_for('users.update') }} ">Update</a>
        <a class="navbar-brand" href=" {{ url_for('blog_posts.create_post') }}">Create Post</a>
        {% else %}
        <a class="navbar-brand" href=" {{url_for('users.login')}} ">Login</a>
        <a class="navbar-brand" href=" {{url_for('users.register')}} ">Register</a>     
        {% endif %}
    </nav>    
    <div class="container">
    {% block content %}
    
    {% endblock %}
    </div>
</body>
</html>

puppycompanyblog/templates/blog_post.html
{% extends "base.html" %}
{% block content %}

    <div class="jumbotron">
        <h1> {{ post.title }} </h1>
        <h2>Written by : {{ post.author.username }} </h2>
        <h3>Published on : {{ post.date.strftime('%B %d, %Y')}} </h3>
        <p>{{ post.text }}</p>
    </div>
 
    {% if post.author == current_user %}
        <div>
            <a href=" {{ url_for('blog_posts.update' , blog_post_id = post.id) }} "> Update </a>
            <button type="button" class="btn btn-danger" data-toggle = 'modal' data-target = "#del_modal" >Delete</button>
        </div>
    {% endif %}

    <div class="modal" tabindex="-1" role="dialog" id="del_modal">
        <div class="modal-dialog" role="document">
          <div class="modal-content">
            <div class="modal-header">
              <h5 class="modal-title">Delete Post</h5>
              <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                <span aria-hidden="true">&times;</span>
              </button>
            </div>
            <div class="modal-body">
              <p>Are you sure you want to delete ?</p>
            </div>
            <div class="modal-footer">
              <button type="button" class="btn btn-secondary" data-dismiss="modal">Cancel</button>
              
                <form action="{{ url_for('blog_posts.delete_post' , blog_post_id = post.id) }}" method="POST">
                    <input type="submit" value="delete" class="btn btn-danger">
                </form>

            </div>
          </div>
        </div>
      </div>

{% endblock %}

puppycompanyblog/templates/create_post.html
{% extends "base.html" %}

{% block content %}

<div class="jumbotron">
        
    <form method="POST">
        {{ form.hidden_tag() }}

        <div class="form-group">
            {{ form.title.label(class = 'form-group') }} 
            {{ form.title(class = 'form-control') }}
        </div>
        <br>
    
        <div class="form-group">
            {{ form.text.label(class = 'form-group') }} 
            {{ form.text(class = 'form-control') }}
        </div>
        <br>
     
        <div class='form-group'>
        {{ form.submit(class = 'btn btn-primary') }}
        </div>
    </form>
</div>

{% endblock %}

puppycompanyblog/templates/home.html
{% extends "base.html" %}

{% block content %}

    <div class="jumbotron">
        <h1>Puppy Company Blog </h1>
    </div>

    <div class="container">
        {% for post in blog_posts.items %}
            <div class="card">
                <div class="card-body">
                    <h2> <a class="card-title" href=" {{ url_for('blog_posts.blog_post' , blog_post_id = post.id) }} "> {{ post.title }} </a></h2>
                    <a href=" {{ url_for('users.user_posts' , username = post.author.username) }} "> Written By : {{ post.author.username }}</a>
                    <p>Published on : {{ post.date.strftime('%Y-%m-%d')}}</p>
                    <a class="btn btn-primary" href=" {{ url_for('blog_posts.blog_post' , blog_post_id = post.id) }} ">Read Blog Post</a>
                </div>
            </div>
        {% endfor %}
    </div>

{% endblock %}

puppycompanyblog/templates/login.html
{% extends "base.html" %}

{% block content %}

<div class="jumbotron">
        
    <form method="POST">
        {{ form.hidden_tag() }}

        <div class="form-group">
            {{ form.email.label(class = 'form-group') }} 
            {{ form.email(class = 'form-control') }}
        </div>
        <br>
    
        <div class="form-group">
            {{ form.password.label(class = 'form-group') }} 
            {{ form.password(class = 'form-control') }}
        </div>
        <br>
     
        <div class='form-group'>
        {{ form.submit(class = 'btn btn-primary') }}
        </div>
    </form>
</div>

{% endblock %}

puppycompanyblog/templates/register.html
{% extends "base.html" %}

{% block content %}

<div class="jumbotron">
        
<form method="POST">
    {{ form.hidden_tag() }}

    <div class="form-group">
    {{ form.username.label(class = 'form-group') }} 
    {{ form.username(class = 'form-control') }}
    </div>
    <br>

    <div class="form-group">
        {{ form.email.label(class = 'form-group') }} 
        {{ form.email(class = 'form-control') }}
    </div>
    <br>
    
    <div class="form-group">
        {{ form.password.label(class = 'form-group') }} 
        {{ form.password(class = 'form-control') }}
    </div>
    <br>
     
    <div class="form-group">
        {{ form.confirm_pass.label(class = 'form-group') }} 
        {{ form.confirm_pass(class = 'form-control') }}
    </div>
    <br>
    <div class='form-group'>
    {{ form.submit(class = 'btn btn-primary') }}
    </div>
    </form>
</div>

{% endblock %}

puppycompanyblog/templates/update.html
{% extends "base.html" %}

{% block content %}

    <div class="jumbotron">
        <div align ='center'>
            <h1>Welcome to the page for {{ current_user.username }}</h1>
            <img src=" {{url_for('static' , filename = 'profile_pics/' + current_user.profile_image)}} ">
        </div>
    </div>

    <div class="container">
        <form method="POST" action="" enctype="multipart/form-data">
            {{ form.hidden_tag() }}

            <div class="form-group">
            {{ form.username.label(class = 'form-group') }} 
            {{ form.username(class = 'form-control') }}
            </div>
            <br>

            <div class="form-group">
                {{ form.email.label(class = 'form-group') }} 
                {{ form.email(class = 'form-control') }}
            </div>
            <br>
            
            <div class="form-group">
                {{ form.picture.label(class = 'form-group') }} 
                {{ form.picture(class = 'form-control') }}
            </div>
            <br>
             
            <div class='form-group'>
            {{ form.submit(class = 'btn btn-primary') }}
            </div>
        </form>
    </div>
{% endblock %}

puppycompanyblog/templates/user_blog_posts.html
{% extends "base.html" %}

{% block content %}

    <div class = "container">
        <div class="jumbotron">
            <div align = 'center'>
                <h1>Welcome to the page of {{ user.username }}</h1>
                <img src=" {{ url_for('static' , filename = 'profile_pics/' + user.profile_image) }} " >
            </div>
        </div>

        {% for post in blog_posts.items %}
            <h2> <a href = " {{ url_for('blog_posts.blog_post' , blog_post_id = post.id) }} "> {{ post.title }} </a></h2>
            Written by : <a href = " {{ url_for('users.user_posts' , username = post.author.username) }} "> {{ post.author.username }} </a>
            <p>Published on : {{ post.date.strftime("%Y-%m-%d") }} </p>
            <br>
            <p>{{post.text}}</p>
            <br>
        {% endfor %}
    </div>

{% endblock %}